default: &default
  adapter: postgresql
  encoding: unicode
  schema_search_path: public
  pool: 5

### Database url example ###
# 'dbtype://{user}:{password}@{host}/{db name}
#
# simple connection without user:
# postgres://localhost/partecipo_development
#
# connection with user and password
# postgres://partecito:password@localhost/partecipo_development
development:
  <<: *default
  url: <%= ENV['RAILS_DATABASE_URL'] || Settings.database_url" %>
test:
  <<: *default
  url: <%= ENV['RAILS_DATABASE_URL'] || Settings.database_url %>

staging:
  <<: *default
  url: <%= ENV['RAILS_DATABASE_URL'] || Settings.database_url %>

production:
  <<: *default
  url: <%= ENV['RAILS_DATABASE_URL'] || Settings.database_url %>
